name: Create Release & Publish to NPM
on:
  workflow_dispatch:
  # push:
  #   tags:
  #     - 'v*'

jobs:
  run:
    name: Release and Publish
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        
      - name: Test
        run: |
          echo "Tags: ${{ github.ref }}"

      # - name: Set up Node.js
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 12
      #     registry-url: https://registry.npmjs.org/

      # Step to create GitHub release
      # - name: Create release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Nusantara Valid ${{ github.ref }}

      # Checkout the tag
      # - name: Checkout tag
      #   uses: actions/checkout@v2
      #   with:
      #     ref: tags/${{ github.ref }}

      # Step to publish to npmjs.org
      # - name: Run publish
      #   run: npm publish --access public
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
