name: Create Release & Publish to NPM
on:
  workflow_dispatch:
  # push:
  #   tags:
  #     - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      
      # Step to create GitHub release
      # - name: Create release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Nusantara Valid ${{ github.ref }}

  publish:
    name: Publish
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      # Checkout the tag
      - name: Checkout tag
        run: |
          git fetch --all --tags --prune
          git checkout $(git describe --tags $(git rev-list --tags --max-count=1))

      # Step to publish to npmjs.org
      # - name: Run publish
      #   run: npm publish --access public
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
